#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libcuckoo
Version  : 0.3
Release  : 1
URL      : https://github.com/efficient/libcuckoo/archive/refs/tags/v0.3.tar.gz
Source0  : https://github.com/efficient/libcuckoo/archive/refs/tags/v0.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSL-1.0
Requires: libcuckoo-data = %{version}-%{release}
Requires: libcuckoo-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev

%description
libcuckoo
=========
libcuckoo provides a high-performance, compact hash table that allows
multiple concurrent reader and writer threads.

%package data
Summary: data components for the libcuckoo package.
Group: Data

%description data
data components for the libcuckoo package.


%package dev
Summary: dev components for the libcuckoo package.
Group: Development
Requires: libcuckoo-data = %{version}-%{release}
Provides: libcuckoo-devel = %{version}-%{release}
Requires: libcuckoo = %{version}-%{release}

%description dev
dev components for the libcuckoo package.


%package license
Summary: license components for the libcuckoo package.
Group: Default

%description license
license components for the libcuckoo package.


%prep
%setup -q -n libcuckoo-0.3
cd %{_builddir}/libcuckoo-0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649805491
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1649805491
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libcuckoo
cp %{_builddir}/libcuckoo-0.3/tests/Catch/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/libcuckoo/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/libcuckoo-c/cuckoo_table_template.cc
/usr/include/libcuckoo-c/cuckoo_table_template.h
/usr/include/libcuckoo/bucket_container.hh
/usr/include/libcuckoo/cuckoohash_config.hh
/usr/include/libcuckoo/cuckoohash_map.hh
/usr/include/libcuckoo/cuckoohash_util.hh

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libcuckoo/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
